const fs = require('fs');
const path = require('path');

const appPath = path.join(__dirname, 'c-units-cpp', 'app');

function run() {
    let replacedCount = 0;
    for (let unit = 1; unit <= 6; unit++) {
        for (let lecture = 1; lecture <= 6; lecture++) {
            const pagePath = path.join(appPath, `unit${unit}`, `L${lecture}`, 'page.tsx');
            if (fs.existsSync(pagePath)) {
                let content = fs.readFileSync(pagePath, 'utf8');
                
                // Target the specific C++ div string generated by generate.js
                const targetText = '<div className="w-8 h-8 rounded-lg bg-blue-600 flex items-center justify-center font-bold text-white shadow-lg shadow-blue-900/20">C++</div>';
                const replacementText = '<img src="/cunits/logo.png" alt="C-Units Logo" className="w-8 h-8 rounded-lg shadow-[0_0_15px_rgba(59,130,246,0.5)]" />';
                
                if (content.includes(targetText)) {
                    content = content.replace(targetText, replacementText);
                    fs.writeFileSync(pagePath, content);
                    replacedCount++;
                }
            }
        }
    }
    console.log(`Successfully replaced logo in ${replacedCount} files.`);
}

run();
